Propagate data cause es2022
MetaMask/rpc-errors pull request #141
Opened 2024-05-13 00:55 UTC by legobeat

Alternative/follow-up to #140.

This utilizes the runtime `Error` constructor `options.cause` to propagate `data.cause`. The explicit assignment of the property in #140 is preserved as a fallback.

This requires change tsconfig [`lib`](https://www.typescriptlang.org/tsconfig/#lib) from `ES2020` to `ES2022`.

2024-05-13 01:02 UTC, legobeat commented on jest.config.js
> +      branches: 91.89,
The reductions here arise from [the fallback](https://github.com/MetaMask/rpc-errors/pull/141/files#diff-51d34864685a38815928276a4a766dfdea2b0f297e7435b73608460e16c145feR38) never triggering since native causes are not used in all tested environments.

Adding test-coverage for the fallback would involve some wider changes to the test suite, I believe.

2024-05-16 05:44 UTC, Mrtenz reviewed
I think this makes sense. When serialised, the cause is still serialised as `data.cause`, right?

2024-05-16 06:38 UTC, legobeat commented
> I think this makes sense. When serialised, the cause is still serialised as data.cause, right?
That's the idea, yes!

2024-05-27 18:16 UTC, rekmarks submitted a review, later dismissed
LGTM.

2024-05-27 21:47 UTC, legobeat commented on tsconfig.json
> +    // Remove custom `cause` field from JsonRpcError when updating
```suggestion
```
Leftover comment

2024-05-28 22:43 UTC, mcmire requested changes

2024-05-28 22:43 UTC, mcmire commented on tsconfig.json
> +    "lib": ["ES2022"],
Hmm, I'm not sure we can do this yet due to React Native not supporting ES2020+. There is a thread in chat about this. Search for "ES2020"; it should be the third message down. (I'll DM it to you.)

2024-05-29 01:55 UTC, legobeat commented on tsconfig.json
> +    "lib": ["ES2022"],
@mcmire Since `es2022` is not an option, which of the following is?
- Adding `dom` instead 
- Defining the `cause` explicitly

2024-05-31 01:51 UTC, legobeat commented
Closing in favor of #140

2024-05-31 01:51 UTC, closed without merging