Migrate to TypeScript
MetaMask/rpc-errors pull request #28
Opened 2020-11-01 03:14 UTC by rekmarks

Migrates this package to TypeScript. In trying to fix the types for this package, which were always terrible and never worked out of the box, I just decided to go ahead with the TypeScript migration.

Bundles two behavioral changes:

- `ERROR_CODES` export renamed to `errorCodes`
- Fixes a bug where a truthy, non-string value could be provided as the `message` for error getters
  - An error will now be thrown instead

A major version bump of this package will follow. 

Fixes #7

2020-11-01 03:20 UTC, rekmarks commented on src/errors.ts
> +      }
Behavioral change 1 of 2:

It was previously possible to pass a truthy, non-string value as the `message` to error getters when using the object signature.

2020-11-01 03:21 UTC, rekmarks commented on src/index.ts
> +  errorCodes,
Behavioral change 2 of 2:

`ERROR_CODES` renamed to `errorCodes`.

2020-11-02 15:32 UTC, brad-decker commented on package.json
> +    "build": "tsc --project .",
tsc will look for tsconfig.json by default, are you doing this to be  explicit and should we be replicating this?

2020-11-02 16:39 UTC, rekmarks commented on package.json
> +    "build": "tsc --project .",
Whymarrh has been doing it, so I was just following his lead. However, if just `tsc` will do it, I think defaults are fine!

2020-11-02 16:40 UTC, rekmarks commented on package.json
> +    "build": "tsc --project .",
c7a21c1

2020-11-02 23:17 UTC, brad-decker requested changes
A few suggestions to make this awesome work 1/10th of a step more awesome.

2020-11-02 23:17 UTC, brad-decker commented on src/classes.ts
> +  constructor(code: number, message: string, data?: unknown) {
Question: can the shape of data be known to the developer? Like when constructing a new Error?

2020-11-02 23:17 UTC, brad-decker commented on src/classes.ts
> +   * @returns {object} The serialized error.
Question: what's our official stance on JSdocs vs typescript? 

My opinion: With a type system, docs should be used to describe intent and purpose, not to provide types.

2020-11-02 23:17 UTC, brad-decker commented on src/index.ts
> +  errorCodes,
Does this require the version bump to be a breaking change?

2020-11-02 23:17 UTC, brad-decker commented on src/classes.ts
> +export interface SerializedEthereumRpcError {
You should probably extends Error here to get the native types for an Error object. This will require some changes (stack is string | undefined, name is required)

2020-11-02 23:23 UTC, rekmarks commented on src/index.ts
> +  errorCodes,
Yes! IMO, the first behavioral change arguably does too, even though it's a bug fix.

From the description:
> A major version bump of this package will follow.

2020-11-02 23:26 UTC, rekmarks commented on src/classes.ts
> +export interface SerializedEthereumRpcError {
I intentionally didn't extend `Error` for these types, because they're intended to follow the [JSON-RPC spec](https://www.jsonrpc.org/specification#error_object), not the native JavaScript error.

2020-11-02 23:26 UTC, brad-decker commented on src/classes.ts
> +  constructor(code: number, message: string, data?: unknown) {
if we had something like
``` class Example<D> {```

and later 
```js
constructor(data: D) {
  this.data = data
}
```

instead of the unknowns, the type could be inferred at call site

```js
const y = new Example({ message: 'issue' })

y.data // <-- object with message key that is a string
```

2020-11-02 23:27 UTC, rekmarks commented on src/classes.ts
> +   * @returns {object} The serialized error.
These were unintentionally left over. Removed in: 26b01c6

2020-11-02 23:40 UTC, rekmarks commented on src/classes.ts
> +  constructor(code: number, message: string, data?: unknown) {
35deae7

2020-11-02 23:42 UTC, brad-decker commented on src/index.ts
> +  errorCodes,
I can read, i swear

2020-11-02 23:43 UTC, brad-decker approved these changes

2020-11-02 23:45 UTC, merged