Rewrite error serialization
MetaMask/rpc-errors pull request #61
Opened 2022-10-27 14:08 UTC by FrederikBolding

Rewrite error serialization to allow any error that conforms to the `JsonRpcError` JSON-compliant type. 

If the error does not conform to this type, it will be wrapped in an Internal RPC error and the original error will be included as the `data.cause`. Any non JSON-compliant props of the error will be removed.

Fixes https://github.com/MetaMask/eth-rpc-errors/issues/51

2022-11-02 15:49 UTC, Mrtenz requested changes

2022-11-02 15:49 UTC, Mrtenz commented on src/utils.ts
> +    return create(error, JsonRpcErrorStruct);
Is `create` necessary here?

2022-11-02 15:49 UTC, Mrtenz commented on src/utils.ts
> + * Constructs a JSON serializable object given an error and a fallbackError.
```suggestion
 * Construct a JSON-serializable object given an error and a `fallbackError`.
```

2022-11-02 15:49 UTC, Mrtenz commented on src/utils.ts
> +  return serialized as SerializedEthereumRpcError;
Why does this need to be cast? Does `buildError` not return something that is compatible with `SerializedEthereumRpcError`?

2022-11-02 15:49 UTC, Mrtenz commented on src/utils.ts
> +  'Invalid internal error. See "data.originalError" for original value. Please report this bug.';
I don't think we should call it "Invalid internal error," that might be a bit confusing?

2022-11-03 09:25 UTC, FrederikBolding commented on src/utils.ts
> +  return serialized as SerializedEthereumRpcError;
I think we can just use `JsonRpcError`

2022-11-03 09:26 UTC, FrederikBolding commented on src/utils.ts
> +    return create(error, JsonRpcErrorStruct);
It should extract the properties from a class, no?

2022-11-03 09:26 UTC, FrederikBolding commented on src/utils.ts
> +    return create(error, JsonRpcErrorStruct);
Or did we figure out that was not the case 🤔

2022-11-03 09:26 UTC, FrederikBolding commented on src/utils.ts
> +  'Invalid internal error. See "data.originalError" for original value. Please report this bug.';
No strong opinion on this. @rekmarks

2022-11-14 22:30 UTC, rekmarks commented on src/utils.ts
> +  'Invalid internal error. See "data.originalError" for original value. Please report this bug.';
`@metamask/rpc-errors internal error: Unspecified error message. Please report this bug.'`

2022-11-14 22:32 UTC, rekmarks commented on src/utils.ts
> +  'Invalid internal error. See "data.originalError" for original value. Please report this bug.';
Errors from this package should perhaps all be prefixed with `@metamask/rpc-errors internal error: `? This is of course contingent on the package being renamed.

2022-11-24 13:18 UTC, Gudahtt commented on src/utils.ts
> +  // If the original error is a partial JSON-RPC error, extract matching keys and merge with fallback error
Unsure about this strategy. The properties of an error should all be related to each other, but this merging might produce confusing outcomes.

It seems that the only required properties for `isJsonRpcError` to return true are `code` and `message`. The message is generally a human-readable explanation of what the code means, sometimes providing additional context as well. But with this merging, we might get totally mismatched messages and codes.

2023-03-08 17:55 UTC, kumavis commented on src/utils.ts
>    { fallbackError = FALLBACK_ERROR, shouldIncludeStack = false } = {},
```suggestion
  { fallbackError = FALLBACK_ERROR, shouldIncludeStack = true } = {},
```

2023-03-08 18:00 UTC, kumavis commented on src/utils.ts
> +    const subset = ERROR_KEYS.reduce((acc, key) => {
this is just a for loop, dont use reduce (confusing)

2023-03-08 18:10 UTC, kumavis commented on src/utils.ts
> +      return { ...fallbackError, message, ...subset };
spread operator ignores all non iterable properties like `stack`

2023-03-08 18:11 UTC, kumavis commented on src/utils.ts
> +    if (isNonEmptyArray(Object.keys(subset))) {
why special behavior if subset is empty

2023-03-09 10:07 UTC, FrederikBolding commented on src/utils.ts
> +  // If the original error is a partial JSON-RPC error, extract matching keys and merge with fallback error
Reverted this to a simpler approach

2023-03-09 10:07 UTC, FrederikBolding commented on src/utils.ts
>    { fallbackError = FALLBACK_ERROR, shouldIncludeStack = false } = {},
Done

2023-03-09 10:07 UTC, FrederikBolding commented on src/utils.ts
> +    const subset = ERROR_KEYS.reduce((acc, key) => {
Deleted this part of the serialization logic

2023-03-09 10:08 UTC, FrederikBolding commented on src/utils.ts
> +      return { ...fallbackError, message, ...subset };
I removed this code, but added tests that the stacks we return are included in `JSON.stringify`

2023-03-09 10:08 UTC, FrederikBolding commented on src/utils.ts
> +    if (isNonEmptyArray(Object.keys(subset))) {
Also deleted

2023-03-09 14:05 UTC, Gudahtt commented on src/utils.ts
> +    const value = error[key as keyof T];
Nit: It looks like this cast is only needed because `T` can be anything. If we restrict it to being an object, TypeScript infers it correctly:

```suggestion
function getCause<T extends RuntimeObject>(error: T): Json {
  return Object.getOwnPropertyNames(error).reduce((acc, key) => {
    const value = error[key];
```

2023-03-09 14:05 UTC, Gudahtt commented on src/utils.ts
> +  return fallbackWithCause as JsonRpcError;
Hmm. We're still returning the original error here without ensuring that it's valid JSON. That seems to be why this cast was needed. That seems contrary to the goal here of creating a "JSON-serializable object". Even if top-level properties are serializable, having nested values that aren't can cause inconsistent behavior between browsers for example.

2023-03-09 14:05 UTC, Gudahtt commented on src/utils.ts
> +function getCause<T>(error: T): Json {
Nit: I see that this name makes _some_ sense since the error being serialized here is being used as the `cause` of the fallback error returned. But `getCause` doesn't seem like the best description of what this function is doing, which is serializing an object.

Maybe this would be better named as `serializeObject`? Or something similar.

2023-03-09 14:05 UTC, Gudahtt commented on src/utils.ts
> +  return fallbackWithCause as JsonRpcError;
If error is an object, it's properly serialized. But if it's an array, the contents remain unserialized. And if it's a primitive value, it's not serialized. Maybe we need a separate strategy for these three cases: object, array, and primitive.

e.g. maybe this would work:

```
function serialize(thing: unknown) {
  if (Array.isArray(thing)) {
    return thing.map(serialize);
  } else if (isObject(thing)) {
    return getCause(thing);
  } else {
    return String(thing)
  }
}
```

Though I didn't confirm that `String(thing)` works for all cases :thinking:. I know `JSON.stringify` blows up in some cases, but maybe not for primitives, maybe that would work too.

2023-03-09 14:05 UTC, Gudahtt commented on src/utils.ts
> +  return fallbackWithCause as JsonRpcError;
Hmm. I don't love the recursion there. It would let anyone crash MetaMask by crafting a stupidly nested error.

Maybe something like this would work:


```
function serialize(thing: unknown) {
  if (Array.isArray(thing)) {
    return thing.map((entry) => {
      if (isValidJson(entry)) {
        return entry;
      } else if (isObject(entry)) {
        return getCause(entry);
      } else {
        // Stringify nested non-JSON arrays and primitives
        // Potentially loses data, but keeps this serialization lightweight and less likely to crash
        return String(entry);
      }
    });
  } else if (isObject(thing)) {
    return getCause(thing);
  } else {
    return String(thing)
  }
}
```

2023-03-09 14:05 UTC, Gudahtt commented on src/utils.ts
> +  const serialized = buildError(error, fallbackError as JsonRpcError);
Nit: This cast does not seem necessary
```suggestion
  const serialized = buildError(error, fallbackError);
```

2023-03-09 14:11 UTC, Mrtenz commented on src/utils.ts
> +    const value = error[key as keyof T];
Is the generic even necessary?
```suggestion
function getCause(error: RuntimeObject): Json {
  return Object.getOwnPropertyNames(error).reduce((acc, key) => {
    const value = error[key];
```

2023-03-09 14:12 UTC, Gudahtt commented on src/utils.ts
> +    const value = error[key as keyof T];
Great point! I don't think it is

2023-03-10 10:13 UTC, FrederikBolding commented on src/utils.ts
> +  return fallbackWithCause as JsonRpcError;
I'm not sure trying to stringify non-JSON compliant primitives is a good idea. I would probably prefer to just return null. What do you think? I pushed a commit that does this.

2023-03-10 11:30 UTC, Gudahtt commented on src/utils.ts
> +  return fallbackWithCause as JsonRpcError;
Makes sense! I wasn't sure if it was a good idea either

2023-03-10 19:19 UTC, kumavis commented on src/utils.ts
> +        ...acc,
doesnt include non-enumerable keys

2023-03-10 19:20 UTC, kumavis commented on src/utils.ts
> +  return Object.getOwnPropertyNames(object).reduce((acc, key) => {
better to just do a for loop and append keys instead of creating new objects over and over again

2023-03-13 10:20 UTC, FrederikBolding commented on src/utils.ts
> +        ...acc,
Removed!

2023-03-13 10:20 UTC, FrederikBolding commented on src/utils.ts
> +  return Object.getOwnPropertyNames(object).reduce((acc, key) => {
Kept the reduce, but now appending keys to the accumulator instead of recreating the object.

2023-03-13 18:56 UTC, kumavis commented on src/utils.ts
> +  if (error instanceof EthereumRpcError) {
instanceof on classes defined in npm packages can be dangerous bc it doesnt work the way you want it when operating of across versions of the package. if this serializer and the error creator are non-deduped copies of the package due to different versions, it will fail to recognize it. better to use duck typing when possible

2023-03-13 18:56 UTC, kumavis commented on src/utils.ts
> +    ...fallbackError,
drops non enumerable properties

2023-03-14 12:51 UTC, FrederikBolding commented on src/utils.ts
> +  if (error instanceof EthereumRpcError) {
Hmm, I'm not sure that duck typing would be safer. We may just end up treating errors not from `eth-rpc-errors` as "native" errors, defeating the purpose of our serialization.

2023-03-14 13:23 UTC, FrederikBolding commented on src/utils.ts
> +    ...fallbackError,
What would you prefer then? Setting `enumerable` to true for `fallbackError`?

2023-04-11 11:49 UTC, Gudahtt commented on src/utils.ts
> +  if (error instanceof EthereumRpcError) {
I guess duck typing here would mean checking for a valid `code` property. So you're saying that that approach would risk treating a third-party error with a `code` as being a JSON-RPC error, resulting in an invalid error.

But the range of valid JSON-RPC error codes is fairly narrow, so I'm not sure that would be very likely to happen. At least if we're checking for the validity of the code, not just the presence of one.

Whereas the other side of this (using two different versions of this library in the same project) is a known scenario in both metamask and extension. We know that `instanceof` would fail to identify errors that are passed up through our middleware stack.

2023-04-11 11:52 UTC, FrederikBolding commented on src/utils.ts
> +  if (error instanceof EthereumRpcError) {
I was under the impression that we would simply be looking for a `serialize` function and calling it if it existed. I was hesitant to make that change, but can do so if the majority would prefer that.

I'm not sure I entirely understand what you would want to check `code` for? 🤔

2023-04-11 11:59 UTC, Gudahtt commented on src/utils.ts
> +  if (error instanceof EthereumRpcError) {
Ah right, I see. This is to check for an unserialized error specifically, so checking for `serialize` makes sense. I was thinking we'd check the code to further narrow this condition to only apply to our json RPC error class.

But maybe that's the wrong idea. If we think of this condition as a _shortcut_/optional optimization, then using `instanceof` is fine, so long as the later steps properly handle an unserialized JSON-RPC error.

2023-04-11 12:00 UTC, Gudahtt commented on src/utils.ts
> +  if (isJsonRpcError(error)) {
It seems that `isJsonRpcError` only checks the object for own properties, it doesn't look up the prototype chain. That means an unserialized error would still pass this check, meaning that we're potentially returning unserialized errors here.

2023-04-11 12:06 UTC, FrederikBolding commented on src/utils.ts
> +    ...fallbackError,
In my opinion, this wouldn't be an issue since we specify the fallback error and it includes the `cause` that may still have a stack.

2023-04-11 12:07 UTC, Gudahtt commented on src/utils.ts
> +    ...fallbackError,
Presumably what we'd want to do here is preserve the `fallbackError` as much as possible, mutating it only to add the cause property.

In this case the fallback error is already expected to be a "serializable object" though, right? So maybe we don't need to worry about non-enumerable properties. Though the JSDoc description should certainly clarify that expectation if that is the case.

2023-04-11 12:10 UTC, Gudahtt commented on src/utils.ts
> +    data: { cause },
I'm curious about why we're putting the cause under `data` here. The error spec has `cause` as a top-level property for errors: https://github.com/tc39/proposal-error-cause

2023-04-11 12:12 UTC, FrederikBolding commented on src/utils.ts
> +    data: { cause },
No strong reason, we can unnest 👍

2023-04-11 12:14 UTC, FrederikBolding commented on src/utils.ts
> +  if (isJsonRpcError(error)) {
Yeah, good point. Any classes that don't satisfy the `instanceof` check may be returned here still. Question is if we should try to extract an RPC error from a class or just call `serialize` when possible? Or both? Or some fourth option 🤔

2023-04-11 12:15 UTC, FrederikBolding commented on src/utils.ts
> +    ...fallbackError,
Yeah, I would expect it to be serializable according to the type. I can add it to the doc string

2023-04-11 12:19 UTC, FrederikBolding commented on src/utils.ts
> +    data: { cause },
Oh actually, this is done to match the JsonRpcError type and specification: https://www.jsonrpc.org/specification#error_object

Not sure whether unnesting is a good idea then 🤔

2023-04-11 12:20 UTC, Gudahtt commented on src/utils.ts
> +  if (isJsonRpcError(error)) {
Calling `serialize` seems adequate for now (at least it'd be an improvement over what we have).

Extracting an error by taking just the properties from the error instance might work too, but that seems a bit riskier than calling `serialize` because that would mean it's a third-party error.

2023-04-11 12:21 UTC, Gudahtt commented on src/utils.ts
> +    data: { cause },
Ahh good catch. Maybe we can update the `serializedError` JSDoc comment instead then, to suggest that the cause will be nested in `data`

2023-04-11 12:22 UTC, Gudahtt commented on src/utils.ts
> +    data: { cause },
Nevermind, that comment is referencing the input not the output. This is already correct then :+1:

2023-04-11 12:25 UTC, Gudahtt commented on src/utils.test.ts
> +  it('handles EthereumRpcError', () => {
Nit: We should add a test case for an object that is like an `EthereumRpcError` except that it doesn't share the same prototype. For the "version mismatch" case.

2023-04-11 12:31 UTC, Gudahtt commented on src/utils.ts
> +    data: { cause },
Nevermind, the comment is already correct! I misread.

2023-04-11 12:53 UTC, Gudahtt submitted a review, later dismissed
LGTM!

2023-04-11 12:56 UTC, Gudahtt approved these changes

2023-04-11 12:57 UTC, Gudahtt commented on src/utils.ts
> +  if (error instanceof EthereumRpcError) {
We have now switched to duck typing, so this thread can be resolved

2023-04-11 12:58 UTC, Mrtenz approved these changes

2023-04-11 13:00 UTC, merged