Migrate to Jest
MetaMask/rpc-errors pull request #66
Opened 2022-11-01 14:16 UTC by FrederikBolding

Migrates to use Jest instead of Tape

2022-11-01 15:38 UTC, Mrtenz requested changes

2022-11-01 15:38 UTC, Mrtenz commented on src/errors.test.ts
> +  expect(err.code === errorCodes.rpc.invalidInput).toBeTruthy();
`expect` should not be nested inside `describe` directly.

2022-11-01 15:38 UTC, Mrtenz commented on src/errors.test.ts
> +  expect(err.message === CUSTOM_ERROR_MESSAGE).toBeTruthy();
These tests can be changed to something like `expect(err.message).toBe(CUSTOM_ERROR_MESSAGE);`. That would be easier to debug on potential test failures too.

2022-11-01 15:38 UTC, Mrtenz commented on src/errors.test.ts
> +  }).toThrowError(/"message" must be/u);
Can we test for full error messages, rather than a partial RegEx?

2022-11-01 15:38 UTC, Mrtenz commented on src/errors.test.ts
> +    ethErrors.rpc.server('bar' as any);
`@ts-expect-error`.

2022-11-01 15:38 UTC, Mrtenz commented on src/errors.test.ts
> +    'Ethereum RPC',
This should describe what is being tested.

2022-11-01 15:38 UTC, Mrtenz commented on src/errors.test.ts
> +      const rpcCode = rpcCodes[key];
?

2022-11-01 15:38 UTC, Mrtenz commented on src/errors.test.ts
> +  it('server', () => {
This should describe what is being tested.

2022-11-01 15:38 UTC, Mrtenz commented on src/errors.test.ts
> +  )('Ethereum Provider', (key, value) => {
This should describe what is being tested.

2022-11-01 15:38 UTC, Mrtenz commented on src/errors.test.ts
> +  it('custom', () => {
This should describe what is being tested.

2022-11-01 15:38 UTC, Mrtenz commented on src/serializeError.test.ts
> +delete validError4.stack;
Can we move this to a separate file?

2022-11-01 15:38 UTC, Mrtenz commented on src/errors.test.ts
> +const CUSTOM_ERROR_MESSAGE = 'foo';
Can we move this to a separate file?

2022-11-01 15:38 UTC, Mrtenz commented on src/serializeError.test.ts
> +  it('invalid error: non-object', () => {
These tests can probably be combined with `it.each`.

2022-11-01 16:18 UTC, FrederikBolding commented on src/errors.test.ts
> +      const rpcCode = rpcCodes[key];
Explained now

2022-11-01 16:18 UTC, FrederikBolding commented on src/errors.test.ts
> +      const rpcCode = rpcCodes[key];
Not sure we can fix

2022-11-01 16:19 UTC, FrederikBolding commented on src/serializeError.test.ts
> +  it('invalid error: non-object', () => {
Not sure it is worth it to spend more time on it

2022-11-02 10:52 UTC, Mrtenz approved these changes

2022-11-02 11:01 UTC, merged